update workflow actions

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -4,7 +4,7 @@ name: Unit Tests
 
 on:
   workflow_run:
-    workflows: ["Super-Linter"]
+    workflows: [ "Lint Check" ]
     types:
       - completed
 
@@ -15,27 +15,38 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-    - name: Set up JDK 11
-      uses: actions/setup-java@v3
-      with:
-        distribution: 'zulu'
-        java-version: '11'
+      - name: Set up JDK 11
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'zulu'
+          java-version: '11'
 
-    - name: Cache Gradle dependencies
-      uses: actions/cache@v3
-      with:
-        path: |
-          ~/.gradle/caches
-          ~/.gradle/wrapper
-        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
-        restore-keys: |
-          gradle-${{ runner.os }}
+      - name: Cache Gradle dependencies
+        uses: actions/cache@v3
+        with:
+          path: |
+            ~/.gradle/caches
+            ~/.gradle/wrapper
+          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
+          restore-keys: |
+            gradle-${{ runner.os }}
 
-    - name: Download dependencies
-      run: ./gradlew build --no-daemon
+      - name: Download dependencies
+        run: ./gradlew build --no-daemon
 
-    - name: Run Unit Tests
-      run: ./gradlew testDebugUnitTest --no-daemon
+      - name: Run Unit Tests
+        run: ./gradlew testDebugUnitTest --no-daemon
+
+  # This job will run if the lint check failed, providing a clear error message
+  lint-failed:
+    if: ${{ github.event.workflow_run.conclusion != 'success' }}
+    name: Lint Check Failed
+    runs-on: ubuntu-latest
+    steps:
+      - name: Fail workflow due to lint check failure
+        run: |
+          echo "Lint check failed. Skipping unit tests."
+          exit 1
